apiVersion: v1
kind: Secret
metadata:
  name: {{ template "veidemann-controller.fullname" . }}-api-key
  labels:
    app: {{ template "veidemann.name" . }}
    chart: {{ template "veidemann.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  apiKeyRoleMapping: {{ .Values.config.apiKeyRoleMapping | b64enc | quote }}
