{{- if .Values.trustedCA.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "veidemann-controller.fullname" . }}
  labels:
    app: {{ template "veidemann-controller.name" . }}
    chart: {{ template "veidemann-controller.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: "kubernetes.io/tls"
data:
  tls.crt: {{ .Values.trustedCA.crt | b64enc }}
  tls.key: {{ .Values.trustedCA.key | b64enc }}
{{- end }}
