apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-controller.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-controller.name" . }}
    chart: {{ template "veidemann-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-controller.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-controller.name" . }}
        release: {{ .Release.Name }}
    {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      volumes:
        - name: log4j-config
          configMap:
            name: {{ template "veidemann-controller.configPrefix" . }}
            items:
              - key: log4j2.xml
                path: log4j2.xml
        - name: envoy-config
          configMap:
            name: {{ template "veidemann-controller.fullname" . }}-envoy
      {{- if .Values.trustedCA.enabled }}
        - name: ca
          secret:
            secretName: {{ default (include "veidemann-controller.fullname" .) .Values.trustedCA.secretName }}
            items:
              - key: tls.crt
                path: tls.crt
      {{- end }}
    {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          envFrom:
            - secretRef:
                name: {{ template "veidemann-controller.configPrefix" . }}-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: {{ default .Values.global.veidemann.rethinkdb.host .Values.config.rethinkdb.host | quote }}
            - name: DB_PORT
              value: {{ default .Values.global.veidemann.rethinkdb.port .Values.config.rethinkdb.port | quote }}
            - name: DB_NAME
              value: {{ default .Values.global.veidemann.rethinkdb.name .Values.config.rethinkdb.name | quote }}
            - name: API_PORT
              value: {{ .Values.service.port | quote }}
            - name: FRONTIER_HOST
            {{- if .Values.config.frontier.host }}
              value: {{ .Values.config.frontier.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-controller.configPrefix" . }}
                  key: frontier.host
            {{- end }}
            - name: FRONTIER_PORT
            {{- if .Values.config.frontier.port }}
              value: {{ .Values.config.frontier.port | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-controller.configPrefix" . }}
                  key: frontier.port
            {{- end }}
            - name: OPENID_CONNECT_ISSUER
            {{- if .Values.config.issuer }}
              value: {{ .Values.config.issuer | quote }}
            {{- end }}
            - name: JAEGER_SERVICE_NAME
              value: {{ include "veidemann-controller.fullname" . | quote }}
            - name: JAEGER_AGENT_HOST
              value: {{ default .Values.global.veidemann.jaeger.agent.host .Values.config.jaeger.agent.host | quote }}
            - name: JAEGER_AGENT_PORT
              value: {{ default .Values.global.veidemann.jaeger.agent.port .Values.config.jaeger.agent.port | quote }}
            {{- if or .Values.global.veidemann.jaeger.sampler.type .Values.config.jaeger.sampler.type }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ default .Values.global.veidemann.jaeger.sampler.type .Values.config.jaeger.sampler.type | quote }}
            {{- end }}
            {{- if or .Values.global.veidemann.jaeger.sampler.param .Values.config.jaeger.sampler.param }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ default .Values.global.veidemann.jaeger.sampler.param .Values.config.jaeger.sampler.param | quote }}
            {{- end }}
          volumeMounts:
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          {{- if .Values.trustedCA.enabled }}
            - name: ca
              mountPath: /veidemann/trustedca/tls.crt
              subPath: tls.crt
          {{- end }}
        - name: {{ .Chart.Name }}-envoy
          image: "{{ .Values.envoy.image.repository }}:{{ default .Chart.AppVersion .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          ports:
            - name: admin
              containerPort: 9901
              protocol: TCP
            - name: grpc-web
              containerPort: 10000
              protocol: TCP
          command:
            - /usr/bin/dumb-init
            - --
          args:
            - /usr/local/bin/envoy
            - -l
            - $loglevel
            - -c
            - /config/envoy.yaml
          livenessProbe:
            tcpSocket:
              port: admin
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: admin
            initialDelaySeconds: 30
          terminationGracePeriodSeconds: 30
          volumeMounts:
            - name: envoy-config
              mountPath: /config
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
