{{- if .Values.ingress.enabled -}}
{{- $fullName := include "veidemann-controller.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grpc-web
  labels:
    app: veidemann
    component: {{ template "veidemann-controller.name" . }}
    chart: {{ template "veidemann-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: "nginx"
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /grpc-web/(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: grpc-web
  {{- end }}
{{- end }}
