apiVersion: v1
kind: Service
metadata:
  name: {{ template "veidemann-controller.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-controller.name" . }}
    chart: {{ template "veidemann-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: grpc
      targetPort: grpc
  selector:
    component: {{ template "veidemann-controller.name" . }}
    release: {{ .Release.Name }}
