{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "rethinkdb-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rethinkdb-backup.name" . }}
    helm.sh/chart: {{ include "rethinkdb-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
{{- end -}}
