{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rethinkdb-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rethinkdb-backup.name" . }}
    helm.sh/chart: {{ include "rethinkdb-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rethinkdb-backup.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rethinkdb-backup.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
