apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "rethinkdb-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rethinkdb-backup.name" . }}
    helm.sh/chart: {{ include "rethinkdb-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  suspend: {{ .Values.suspend }}
  schedule: {{ .Values.cronExpression | quote }}
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "rethinkdb-backup.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "rethinkdb-backup.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - "dump"
                - "--export"
                - {{ .Values.export | quote }}
                - "--password-file"
                - "/secret/rethinkdb-password"
              env:
                - name: FILE_PREFIX
                  value: {{ .Values.filePrefix | quote }}
              volumeMounts:
                - name: data
                  mountPath: /data
                {{- if .Values.persistence.data.subPath }}
                  subPath: {{ .Values.persistence.data.subPath }}
                {{- end }}
                - name: temp
                  mountPath: /temp
                - name: secret
                  mountPath: /secret
                  readOnly: true
              resources:
{{- toYaml .Values.resources | nindent 16 }}
            - name: "{{ .Chart.Name }}-proxy"
              image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
              imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
              ports:
                - name: cluster
                  containerPort: {{ .Values.proxy.ports.cluster }}
                - name: driver
                  containerPort: {{ .Values.proxy.ports.driver }}
                - name: admin
                  containerPort: {{ .Values.proxy.ports.admin }}
              args:
                - "--bind-cluster"
                - "$(POD_IP)"
                - "--no-http-admin"
                - "--no-update-check"
              env:
                - name: PROXY
                  value: "true"
                - name: RETHINK_CLUSTER_SERVICE
                  value: {{ .Values.proxy.clusterService | quote }}
                - name: RETHINKDB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "rethinkdb-backup.fullname" . }}
                      key: rethinkdb-password
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              resources:
{{- toYaml .Values.proxy.resources | nindent 16 }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
{{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
{{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
{{- toYaml . | nindent 12 }}
        {{- end }}
          volumes:
            - name: secret
              secret:
                secretName: {{ include "rethinkdb-backup.fullname" . }}
                items:
                  - key: rethinkdb-password
                    path: rethinkdb-password
            - name: data
            {{- if .Values.persistence.data.enabled }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.data.existingClaim | default (include "rethinkdb-backup.fullname" .) }}
            {{- else }}
              emptyDir: {}
            {{- end }}
            - name: temp
            {{- if .Values.persistence.temp.enabled }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.temp.existingClaim | default (include "rethinkdb-backup.fullname" .) }}-temp
            {{- else }}
              emptyDir: {}
            {{- end -}}
