apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rethinkdb-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rethinkdb-backup.name" . }}
    helm.sh/chart: {{ include "rethinkdb-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: {{ include "rethinkdb-backup.fullname" . }}
      labels:
        app.kubernetes.io/name: {{ include "rethinkdb-backup.name" . }}
        helm.sh/chart: {{ include "rethinkdb-backup.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.persistence.data.subPath }}
              subPath: {{ .Values.persistence.data.subPath }}
            {{- end }}
            - name: temp
              mountPath: /temp
            - name: secret
              mountPath: /secret
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: "{{ .Chart.Name }}-proxy"
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
            - name: cluster
              containerPort: {{ .Values.proxy.ports.cluster }}
            - name: driver
              containerPort: {{ .Values.proxy.ports.driver }}
            - name: admin
              containerPort: {{ .Values.proxy.ports.admin }}
          args:
            - "--bind-cluster"
            - "$POD_IP"
            - "--runuser"
            - "rethinkdb"
            - "--rungroup"
            - "rethinkdb"
            - "--no-http-admin"
            - "--no-update-check"
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: {{ .Values.proxy.clusterService | quote }}
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rethinkdb-backup.fullname" . }}
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: secret
          secret:
            secretName: {{ include "rethinkdb-backup.fullname" . }}
            items:
              - key: rethinkdb-password
                path: rethinkdb-password
        - name: data
        {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim | default (include "rethinkdb-backup.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: temp
        {{- if .Values.persistence.temp.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.temp.existingClaim | default (include "rethinkdb-backup.fullname" .) }}-temp
        {{- else }}
          emptyDir: {}
        {{- end -}}
