{{- if .Values.standalone }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rethinkdb-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rethinkdb-backup.name" . }}
    helm.sh/chart: {{ include "rethinkdb-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.config.rethinkdb.password | b64enc | quote }}
{{- end }}
