{{- $global := .Values.global.veidemann -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-harvester.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-harvester.name" . }}
    chart: {{ template "veidemann-harvester.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-harvester.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-harvester.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: workdir
          emptyDir: {}
        - name: log4j-config
          configMap:
            name: {{ template "veidemann-harvester.configPrefix" . }}
            items:
            - key: log4j2.xml
              path: log4j2.xml
        - name: dshm
          emptyDir:
            medium: Memory
        - name: cache-certificate
          secret:
            secretName: {{ .Release.Name }}-veidemann-cache
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.proxy.image.repository }}:{{ default .Chart.AppVersion .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        {{- with .Values.proxy.ports }}
          ports:
{{ toYaml . | indent 12 }}
        {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "veidemann-harvester.configPrefix" . }}-rethinkdb-env
                optional: false
            - secretRef:
                name: {{ template "veidemann-harvester.configPrefix" . }}-rethinkdb-env
                optional: false
          {{- if not .Values.global.veidemann.jaeger }}
            - configMapRef:
                name: {{ template "veidemann-harvester.configPrefix" . }}-jaeger-env
                optional: true
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: BROWSER_WS_ENDPOINT
              value: {{ .Values.proxy.config.browserWSEndpoint | quote }}
            - name: MAX_OPEN_SESSIONS
              value: {{ .Values.proxy.config.maxOpenSessions | quote }}
            - name: FRONTIER_HOST
            {{- if or .Values.proxy.config.frontier.host $global.mesh.host }}
              value: {{ default .Values.proxy.config.frontier.host $global.mesh.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: frontier.host
            {{- end }}
            - name: FRONTIER_PORT
            {{- if or .Values.proxy.config.frontier.port $global.mesh.port}}
              value: {{ default .Values.proxy.config.frontier.port $global.mesh.port| quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: frontier.port
            {{- end }}
            - name: CONTENT_WRITER_HOST
            {{- if or .Values.proxy.config.contentWriter.host $global.mesh.host }}
              value: {{ default .Values.proxy.config.contentWriter.host $global.mesh.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: contentWriter.host
            {{- end }}
            - name: CONTENT_WRITER_PORT
            {{- if or .Values.proxy.config.contentWriter.port $global.mesh.port}}
              value: {{ default .Values.proxy.config.contentWriter.port $global.mesh.port| quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: contentWriter.port
            {{- end }}
            - name: DNS_RESOLVER_HOST
            {{- if or .Values.proxy.config.dnsResolver.host $global.mesh.host }}
              value: {{ default .Values.proxy.config.dnsResolver.host $global.mesh.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: dnsResolver.host
            {{- end }}
            - name: DNS_RESOLVER_PORT
            {{- if or .Values.proxy.config.dnsResolver.port $global.mesh.port}}
              value: {{ default .Values.proxy.config.dnsResolver.port $global.mesh.port| quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: dnsResolver.port
            {{- end }}
            - name: CACHE_HOST
            {{- if .Values.proxy.config.cache.host }}
              value: {{ .Values.proxy.config.cache.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: cache.host
            {{- end }}
            - name: CACHE_PORT
            {{- if .Values.proxy.config.cache.port }}
              value: {{ .Values.proxy.config.cache.port | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-harvester.configPrefix" . }}
                  key: cache.port
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.proxy.config.javaOpts | quote }}
          {{- with .Values.global.veidemann.jaeger }}
            - name: JAEGER_AGENT_HOST
              value: {{ .agent.host | quote }}
            - name: JAEGER_AGENT_PORT
              value: {{ .agent.port | quote }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ .sampler.type | quote }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ .sampler.param | quote }}
          {{- end }}
        {{- with .Values.proxy.livenessProbe }}
          livenessProbe:
{{ toYaml . | indent 12 }}
        {{- end }}
          readinessProbe:
        {{- with .Values.proxy.readinessProbe }}
{{ toYaml . | indent 12 }}
        {{- end }}
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
            - name: cache-certificate
              mountPath: "/ca-certificates"
              readOnly: true
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}

        # Browser container
        - name: {{ .Chart.Name }}-browser
          image: "{{ .Values.browser.image.repository }}:{{ .Values.browser.image.tag }}"
          imagePullPolicy: {{ .Values.browser.image.pullPolicy }}
          ports:
{{ toYaml .Values.browser.ports | indent 12 }}
          env:
          - name: CONNECTION_TIMEOUT
            value: {{ .Values.browser.config.connectionTimeout | quote }}
          livenessProbe:
{{ toYaml .Values.browser.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.browser.readinessProbe | indent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          resources:
{{ toYaml .Values.browser.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
