dependencies:
# Core
- name: veidemann-cache
  version: 1.0.1
  repository: file://../veidemann-cache

- name: veidemann-contentwriter
  version: 1.0.4
  repository: file://../veidemann-contentwriter

- name: veidemann-controller
  version: 1.0.3
  repository: file://../veidemann-controller

- name: veidemann-db-initializer
  version: 1.0.4
  repository: file://../veidemann-db-initializer

- name: veidemann-dns-resolver
  version: 1.0.0
  repository: file://../veidemann-dns-resolver

- name: veidemann-frontier
  version: 1.0.4
  repository: file://../veidemann-frontier

- name: veidemann-harvester
  version: 1.1.3
  repository: file://../veidemann-harvester

- name: veidemann-robotsevaluator-service
  version: 1.0.3
  repository: file://../veidemann-robotsevaluator-service

- name: veidemann-contentexplorer
  version: 1.0.5
  repository: file://../veidemann-contentexplorer

# Dashboard
- name: veidemann-dashboard
  version: 1.0.1
  repository: file://../veidemann-dashboard
  condition: veidemann-dashboard.enabled
  tags:
  - dashboard

- name: veidemann-api-gateway
  version: 1.0.0
  repository: file://../veidemann-api-gateway
  condition: veidemann-api-gateway.enabled
  tags:
  - dashboard

- name: veidemann-dashboard-documentation
  version: 1.0.0
  repository: file://../veidemann-dashboard-documentation
  condition: veidemann-dashboard-documentation.enabled
  tags:
  - dashboard

# Validation
- name: veidemann-warcvalidator
  version: 1.0.1
  repository: file://../veidemann-warcvalidator
  condition: veidemann-warcvalidator.enabled
  tags:
  - validation

- name: veidemann-warcvalidator-api
  version: 1.0.0
  repository: file://../veidemann-warcvalidator-api
  condition: veidemann-warcvalidator-api.enabled
  tags:
  - validation

# Metrics
- name: veidemann-metrics
  version: 1.0.1
  repository: file://../veidemann-metrics
  condition: veidemann-metrics.enabled
  tags:
  - metrics

# Tracing
- name: jaeger
  version: 0.7.0
  repository: "@incubator"
  condition: jaeger.enabled
  tags:
  - tracing

# Identity provider
- name: dex
  version: 0.5.0
  repository: "@stable"
  condition: dex.enabled
  tags:
  - idp

# Service mesh
- name: mesh
  repository: file://../mesh
  version: 0.2.4
  condition: mesh.enabled
  tags:
  - mesh

# Database
- name: rethinkdb
  version: 0.2.1
  repository: file://../rethinkdb
  condition: rethinkdb.enabled
  tags:
  - database
