# Default values for veidemann.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tags:
  database: true
  mesh: false
  tracing: false
  idp: false
  metrics: false
  validation: false
  dashboard: false

nameOverride: ""
fullnameOverride: ""

# If any of the pvc's defined below should be used as existingClaim for
# veidemann-contentwriter, veidemann-contentexplorer or veidemann-warcvalidator
# set their existingClaim value to the sentinel value "veidemann".
persistence:
  warcs:
    enabled: true
    accessMode: ReadWriteMany
    size: 1Gi
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""

    # Annotations for the Persistent Volume Claim
    annotations: {}
    # helm.sh/resource-policy: keep

  invalidwarcs:
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""

    # Annotations for the Persistent Volume Claim
    annotations: {}
    # helm.sh/resource-policy: keep

  validwarcs:
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""

    # Annotations for the Persistent Volume Claim
    annotations: {}
    # helm.sh/resource-policy: keep

  delivery:
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""

    # Annotations for the Persistent Volume Claim
    annotations: {}
    # helm.sh/resource-policy: keep

tls:
  create: false
  key: ""
  crt: ""

# the use of global is needed because of a kubernetes
# bug that does not resolve environment variables (e.g. "$(NODE_NAME)")
# when value is inserted into pod via configMapRef
global:
  veidemann: {}
  # mesh: {}
  #   host: ""
  #   port: ""
  # jaeger:
  #   agent:
  #     host: "jaeger-agent"
  #     port: "5775"
  #   sampler:
  #     type: "probabilistic"
  #     param: "0.1"

# default config values as used by configmap/secrets
default:
  controller:
    host: "veidemann-controller"
    port: "7700"

  frontier:
    host: "veidemann-frontier"
    port: "7700"

  harvester:
    host: "veidemann-harvester"
    port: "8080"

  contentWriter:
    host: "veidemann-contentwriter"
    port: "8082"

  dnsResolver:
    host: "veidemann-dnsresolver"
    port: "8053"

  robotsEvaluator:
    host: "veidemann-robotsevaluator-service"
    port: "7053"

  cache:
    host: "veidemann-cache"
    port: "3128"

  rethinkdb:
    host: "rethinkdb-proxy"
    port: "28015"
    name: "veidemann"
    user: "admin"
    password: "rethinkdb"

  jaeger:
    agent:
      host: "jaeger-agent"
      port: "5775"
    sampler:
      type: "probabilistic"
      param: "0.5"

  log4j2:
    xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <Configuration status="WARN" monitorInterval="0">
          <Appenders>
              <Console name="Console" target="SYSTEM_OUT">
                  <PatternLayout
                          pattern="%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%thread] %-5level %logger{36} - %MDC %msg %ex{full}%n"/>
              </Console>
          </Appenders>
          <Loggers>
              <Logger name="no.nb.nna.veidemann" level="info" additivity="false">
                  <AppenderRef ref="Console"/>
              </Logger>
              <Root level="error">
                  <AppenderRef ref="Console"/>
              </Root>
          </Loggers>
      </Configuration>

# config values overrides default values
config:
  controller:
    host: ""
    port: ""

  frontier:
    host: ""
    port: ""

  harvester:
    host: ""
    port: ""

  contentWriter:
    host: ""
    port: ""

  dnsResolver:
    host: ""
    port: ""

  robotsEvaluator:
    host: ""
    port: ""

  cache:
    host: ""
    port: ""

  rethinkdb:
    host: ""
    port: ""
    name: ""
    user: ""
    password: ""

  jaeger:
    agent:
      host: ""
      port: ""
    sampler:
      type: ""
      param: ""

  log4j2:
    xml: ""

veidemann-db-initializer:
  annotations:
    "helm.sh/hook": "post-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"

veidemann-contentwriter:
  persistence:
    enabled: true
    existingClaim: "warcs"

veidemann-contentexplorer:
  persistence:
    enabled: true
    existingClaim: "warcs"

veidemann-warcvalidator:
  persistence:
    warcs:
      enabled: true
      existingClaim: "warcs"

veidemann-cache:
  cache:
    dnsServers: "veidemann-dnsresolver"

rethinkdb:
  cluster:
    replicas: 1

dex:
  ingress:
    path: /dex
  config:
    storage:
      type: kubernetes
      config:
        inCluster: true
    logger:
      level: "debug"
      format: "text"
    oauth2:
      skipApprovalScreen: true
      responseTypes: ["code", "token", "id_token"]

jaeger:
  cassandra:
    config:
      cluster_size: 1
      max_heap_size: 512M
      heap_new_size: 256M
    persistence:
      enabled: false
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
      limits:
        memory: 2Gi
        cpu: 400m
