apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-contentwriter.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-contentwriter.name" . }}
    chart: {{ template "veidemann-contentwriter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-contentwriter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: {{ template "veidemann-contentwriter.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - emptyDir: {}
          name: workdir
        - name: warcs
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: log4j-config
          configMap:
            name: {{ .Release.Name }}-veidemann
            items:
            - key: log4j2.xml
              path: log4j2.xml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - mountPath: /warcs
              name: warcs
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: API_PORT
              value: "8082"
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FILE_PREFIX
              value: {{ .Values.config.filePrefix | quote }}
            - name: WARC_WRITER_POOL_SIZE
              value: {{ .Values.config.warc.writer.poolSize | quote }}
            - name: WARC_SIZE
              value: {{ .Values.config.warc.size | quote }}
            - name: WARC_COMPRESS
              value: {{ .Values.config.warc.compress | quote }}
            - name: DB_HOST
              value: {{ .Values.config.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.config.db.port | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.db.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.db.secretName }}
                  key: password
            - name: JAEGER_AGENT_HOST
              value: {{ .Values.config.jaeger.agent.host | quote }}
            - name: JAEGER_AGENT_PORT
              value: {{ .Values.config.jaeger.agent.port | quote }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ .Values.config.jaeger.sampler.type | quote }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ .Values.config.jaeger.sampler.param | quote }}          
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
