apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-robotsevaluator-service.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-robotsevaluator-service.name" . }}
    chart: {{ template "veidemann-robotsevaluator-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-robotsevaluator-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-robotsevaluator-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: log4j-config
          configMap:
            name: {{ template "veidemann-robotsevaluator-service.configPrefix" . }}
            items:
            - key: log4j2.xml
              path: log4j2.xml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          envFrom:
            - configMapRef:
                name: {{ template "veidemann-robotsevaluator-service.configPrefix" . }}-rethinkdb-env
                optional: false
            - secretRef:
                name: {{ template "veidemann-robotsevaluator-service.configPrefix" . }}-rethinkdb-env
                optional: false
          {{- if not .Values.global.veidemann.jaeger }}
            - configMapRef:
                name: {{ template "veidemann-robotsevaluator-service.configPrefix" . }}-jaeger-env
                optional: true
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: API_PORT
              value: {{ .Values.service.port | quote }}
            - name: PROXY_HOST
            {{- if .Values.config.proxy.host }}
              value: {{ .Values.config.proxy.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-robotsevaluator-service.configPrefix" . }}
                  key: harvester.host
            {{- end }}
            - name: PROXY_PORT
            {{- if .Values.config.proxy.host }}
              value: {{ .Values.config.proxy.port | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-robotsevaluator-service.configPrefix" . }}
                  key: harvester.port
            {{- end }}
          {{- with .Values.global.veidemann.jaeger }}
            - name: JAEGER_AGENT_HOST
              value: {{ .agent.host | quote }}
            - name: JAEGER_AGENT_PORT
              value: {{ .agent.port | quote }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ .sampler.type | quote }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ .sampler.param | quote }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
