apiVersion: v1
kind: Service
metadata:
  name: {{ template "veidemann-robotsevaluator.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-robotsevaluator.name" . }}
    chart: {{ template "veidemann-robotsevaluator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
      protocol: TCP
  selector:
    component: {{ template "veidemann-robotsevaluator.name" . }}
    release: {{ .Release.Name }}

