# Default values for veidemann-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-metrics
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  externalMetricsPort: 9301
  internalMetricsPort: 9301

resources: {}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            component: veidemann-frontier
        topologyKey: kubernetes.io/hostname

livenessProbe: {}

readinessProbe: {}

config:
  rethinkdb:
    host: ""
    port: ""
    name: ""

global:
  veidemann:
    rethinkdb:
      host: ""
      port: ""
      name: ""
