apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "namerd.fullname" . }}
  labels:
    app: {{ template "namerd.name" . }}
    chart: {{ template "namerd.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "namerd.name" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "namerd.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      volumes:
        - name: namerd-config
          configMap:
            name: "{{ template "namerd.fullname" . }}-config"
      serviceAccountName: {{ template "namerd.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /io.buoyant/namerd/config/config.yaml
          ports:
            - name: mesh
              containerPort: {{ .Values.service.meshPort }}
            - name: sync
              containerPort: {{ .Values.service.syncPort }}
            - name: api
              containerPort: {{ .Values.service.apiPort }}
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
          volumeMounts:
            - name: namerd-config
              mountPath: "/io.buoyant/namerd/config"
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 14 }}
        - name: {{ .Chart.Name }}-kubectl
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          args:
            - "proxy"
            - "-p"
            - "8001"
          resources:
{{ toYaml .Values.kubectl.resources | indent 14 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
