{{- if .Values.rbac.create }}
# grant namerd permisisons to third party resources for dtab storage
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "namerd.fullname" . }}
  labels:
    app: {{ template "namerd.name" . }}
    chart: {{ template "namerd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

rules:
- apiGroups: ["l5d.io"]
  resources: ["dtabs"]
  verbs: ["get", "watch", "list", "update", "create"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "namerd.fullname" . }}
  labels:
    app: {{ template "namerd.name" . }}
    chart: {{ template "namerd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "namerd.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "namerd.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}