kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "namerd.fullname" . }}-namerctl-script
  labels:
    app: {{ template "namerd.name" . }}
    chart: {{ template "namerd.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  createNs.sh: {{ toYaml .Values.createNamespace | indent 2 }}
