apiVersion: v1
kind: Service
metadata:
  name: {{ template "namerd.fullname" . }}
  labels:
    app: {{ template "namerd.name" . }}
    chart: {{ template "namerd.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mesh
    port: {{ .Values.service.meshPort }}
  - name: sync
    port: {{ .Values.service.syncPort }}
  - name: api
    port: {{ .Values.service.apiPort }}
  - name: admin
    port: {{ .Values.service.adminPort }}
  selector:
    app: {{ template "namerd.name" . }}
    release: "{{ .Release.Name }}"
