# Default values for veidemann-frontier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-frontier
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports:
    grpc:
      port: 7700
      targetPort: grpc
      protocol: TCP
    http-metrics:
      port: 9301
      targetPort: http-metrics
      protocol: TCP

ports:
  - name: grpc
    containerPort: 7700
    protocol: TCP
  - name: http-metrics
    containerPort: 9301
    protocol: TCP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}

podAnnotations: {}

# How long kubernetes will wait before terminating pod
# Should be set higher than config value of same name
terminationGracePeriodSeconds: 100

config:
  terminationGracePeriodSeconds: 60
  robotsEvaluator:
    host: ""
    port: ""
  dnsResolver:
    host: ""
    port: ""
  oosHandler:
    host: ""
    port: ""
  rethinkdb:
    host: ""
    port: ""
    name: ""
  javaOpts: ""
  jaeger:
    agent:
      host: ""
      port: ""
    sampler:
      type: ""
      param: ""

global:
  veidemann:
    rethinkdb:
      host: ""
      port: ""
      name: ""
    jaeger:
      agent:
        host: ""
        port: ""
      sampler:
        type: ""
        param: ""
