apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-warcvalidator.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-warcvalidator.name" . }}
    chart: {{ template "veidemann-warcvalidator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-warcvalidator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: {{ template "veidemann-warcvalidator.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: warcs
        {{- if .Values.persistence.warcs.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.warcs.name }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: validwarcs
        {{- if .Values.persistence.validwarcs.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.validwarcs.name }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: invalidwarcs
        {{- if .Values.persistence.invalidwarcs.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.invalidwarcs.name }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: delivery
        {{- if .Values.persistence.delivery.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.delivery.name }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /validwarcs
              name: validwarcs
            - mountPath: /warcs
              name: warcs
            - mountPath: /invalidwarcs
              name: invalidwarcs
            - mountPath: /delivery
              name: delivery
          env:
            - name: SLEEP_TIME
              value: {{ .Values.config.sleepTime | quote }}
            - name: DB_HOST
              value: {{ .Values.config.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.config.db.port | quote }}
            - name: DB_NAME
              value: {{ .Values.config.db.name | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.db.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.db.secretName }}
                  key: password
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
