apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-warcvalidator.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-warcvalidator.name" . }}
    chart: {{ template "veidemann-warcvalidator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-warcvalidator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-warcvalidator.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        {{- $root := . -}}
        {{- range $name, $persistence := .Values.persistence }}
        - name: {{ $name }}
        {{- if $persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "veidemann-warcvalidator.claimName" (dict "name" $name "root" $root) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- end }}
        - name: log4j-config
          configMap:
            name: {{ template "veidemann-warcvalidator.configPrefix" . }}
            items:
              - key: log4j2.xml
                path: log4j2.xml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
            - mountPath: /validwarcs
              name: validwarcs
            - mountPath: /warcs
              name: warcs
            - mountPath: /invalidwarcs
              name: invalidwarcs
            - mountPath: /delivery
              name: delivery
          env:
            - name: SLEEP_TIME
              value: {{ .Values.config.sleepTime | quote }}
          envFrom:
            - configMapRef:
                name: {{ template "veidemann-warcvalidator.configPrefix" . }}-rethinkdb-env
                optional: false
            - secretRef:
                name: {{ template "veidemann-warcvalidator.configPrefix" . }}-rethinkdb-env
                optional: false
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
