apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "veidemann-cache.fullname" . }}-balancer"
  labels:
    app: veidemann
    component: "{{ template "veidemann-cache.name" . }}-balancer"
    chart: {{ template "veidemann-cache.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.balancerReplicaCount }}
  selector:
    matchLabels:
      component: "{{ template "veidemann-cache.name" . }}-balancer"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: "{{ template "veidemann-cache.name" . }}-balancer"
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "veidemann-cache.serviceAccountName" . }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: "{{ .Chart.Name }}-balancer"
          image: "{{ .Values.cache.image.repository }}:{{ default .Chart.AppVersion .Values.cache.image.tag }}"
          imagePullPolicy: {{ .Values.cache.image.pullPolicy }}
          args:
            - "squid"
            - "-b"
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          env:
            - name: DNS_SERVERS
              value: {{ include "veidemann-cache.dnsServers" . | quote }}
            - name: SERVICE_NAME
              value: {{ template "veidemann-cache.fullname" . }}
          resources:
{{ toYaml .Values.cache.resources | indent 12 }}
      {{- if .Values.exporter.enabled }}
        - name: {{ .Chart.Name}}-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: http-metrics
              containerPort: 9301
              protocol: TCP
          args:
            - "-listen"
            - "0.0.0.0:9301"
          resources:
{{ toYaml .Values.exporter.resources | indent 12 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
