{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "veidemann-cache.serviceAccountName" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-cache.name" . }}
    chart: {{ template "veidemann-cache.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
