apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "veidemann-cache.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-cache.name" . }}
    chart: {{ template "veidemann-cache.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "veidemann-cache.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      component: {{ template "veidemann-cache.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-cache.name" . }}
        release: {{ .Release.Name }}
    {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.cache.image.repository }}:{{ default .Chart.AppVersion .Values.cache.image.tag }}"
          imagePullPolicy: {{ .Values.cache.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          env:
            - name: DNS_SERVERS
              value: {{ include "veidemann-cache.dnsServers" . | quote }}
          volumeMounts:
            - name: workdir
              mountPath: /var/cache/squid
            - name: cache-certificate
              mountPath: "/ca-certificates"
              readOnly: true
          resources:
{{ toYaml .Values.cache.resources | indent 12 }}
      {{- if .Values.exporter.enabled }}
        - name: {{ .Chart.Name}}-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: http-metrics
              containerPort: 9301
              protocol: TCP
          args:
            - "-listen"
            - "0.0.0.0:9301"
          resources:
{{ toYaml .Values.exporter.resources | indent 12 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: cache-certificate
          secret:
            secretName: {{ template "veidemann-cache.fullname" . }}
        - name: workdir
{{- if not .Values.persistence.enabled }}
          emptyDir: {}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: workdir
        labels:
          app: veidemann
          component: {{ template "veidemann-cache.name" . }}
          release: {{ .Release.Name }}
      {{- with .Values.persistence.annotations }}
        annotations:
{{ toYaml . | indent 10 }}
      {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
      {{- end }}
      {{- end }}
{{- end }}
