# Default values for veidemann-db-initializer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-db-initializer
  tag: ""
  pullPolicy: Always
  restartPolicy: Never

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}

config:
  db:
    host: rethinkdb-proxy
    port: 28015
    name: veidemann
    secretName: rethinkdb
