# Default values for veidemann-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports:
    http-alt:
      port: 8080
      targetPort: http-alt
      protocol: TCP
    debug:
      port: 3000
      targetPort: debug
      protocol: TCP
    http-metrics:
      port: 9301
      targetPort: http-metrics
      protocol: TCP

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}

podAnnotations: {}

proxy:
  image:
    repository: norsknettarkiv/veidemann-recorderproxy
    tag: "0.2.0"
    pullPolicy: IfNotPresent
  ports:
    - name: http
      containerPort: 9900
      protocol: TCP
  config:
    dnsResolver:
      host: ""
      port: ""
    cache:
      host: ""
      port: ""

browserController:
  image:
    repository: norsknettarkiv/veidemann-harvester
    tag: ""
    pullPolicy: IfNotPresent

  ports:
  - name: http-alt
    containerPort: 8080
    protocol: TCP
  - name: http-metrics
    containerPort: 9301
    protocol: TCP

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  livenessProbe: {}
    #    tcpSocket:
    #      port: http
    #    initialDelaySeconds: 10
    #    periodSeconds: 10
  readinessProbe: {}
    #    tcpSocket:
    #      port: http
    #    initialDelaySeconds: 10
    #    periodSeconds: 10

  config:
    browserWSEndpoint: ws://localhost:3000/?--proxy-server=localhost:8080
    maxOpenSessions: 2
    javaOpts: ""
    frontier:
      host: ""
      port: ""
    robotsEvaluator:
      host: ""
      port: ""
    contentWriter:
      host: ""
      port: ""
    rethinkdb:
      host: ""
      port: ""
      name: ""
    jaeger:
      agent:
        host: ""
        port: ""
      sampler:
        type: ""
        param: ""

browser:
  image:
    repository:  browserless/chrome
    tag: 1.5.0-puppeteer-1.14.0
    pullPolicy: IfNotPresent
  ports:
    - name: debug
      containerPort: 3000
  resources: {}

  livenessProbe:
    httpGet:
      path: /json/version
      port: debug
    initialDelaySeconds: 5
    periodSeconds: 5

  readinessProbe:
    httpGet:
      path: /json/version
      port: debug
    initialDelaySeconds: 5
    periodSeconds: 5

  config:
    connectionTimeout: "600000"

global:
  veidemann:
    rethinkdb:
      host: ""
      port: ""
      name: ""
    jaeger:
      agent:
        host: ""
        port: ""
      sampler:
        type: ""
        param: ""
