# Default values for veidemann-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-harvester
  tag: ""
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports:
    http:
      port: 9090
      targetPort: http
      protocol: TCP
    http-alt:
      port: 8080
      targetPort: http-alt
      protocol: TCP
    debug:
      port: 3000
      targetPort: debug
      protocol: TCP

ports:
  - name: http
    containerPort: 9090
    protocol: TCP
  - name: http-alt
    containerPort: 8080
    protocol: TCP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

config:
  browserWSEndpoint: ws://localhost:3000/?--proxy-server=localhost:8080
  frontier:
    host: $(NODE_NAME)
    port: 4340
  contentWriter:
    host: $(NODE_NAME)
    port: 4340
  dnsResolver:
    host: $(NODE_NAME)
    port: 4340
  cache:
    host: veidemann-cache
  db:
    host: rethinkdb-proxy
    port: 28015
    name: veidemann
    secretName: rethinkdb
  maxOpenSessions: 2
  livenessProbe: {}
#    tcpSocket:
#      port: http
#    initialDelaySeconds: 10
#    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
  jaeger:
    agent:
      host: $(NODE_NAME)
      port: 5775
    sampler:
      type: probabilistic
      param: 0.1
  javaOpts: ""

browser:
  image:
    repository:  browserless/chrome
    tag: release-puppeteer-1.5.0
    pullPolicy: IfNotPresent
  ports:
    - name: debug
      containerPort: 3000
  resources: {}
  livenessProbe:
    httpGet:
      path: /json/version
      port: debug
    initialDelaySeconds: 10
    periodSeconds: 5
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
  config:
    connectionTimeout: "60000"

nodeSelector: {}

tolerations: []

affinity: {}
