# Secret for signing MITM responses from cache
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "veidemann-cache.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-cache.name" . }}
    chart: {{ template "veidemann-cache.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{ (.Files.Glob "cert/*").AsSecrets | indent 2 }}
