apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-api-gateway.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-api-gateway.name" . }}
    chart: {{ template "veidemann-api-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-api-gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-api-gateway.name" . }}
        release: {{ .Release.Name }}
    {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CONTROLLER_HOST
          {{- if .Values.config.controller.host }}
            value: {{ .Values.config.controller.host | quote }}
          {{- else }}
            valueFrom:
              configMapKeyRef:
                name: {{ template "veidemann-api-gateway.configPrefix" . }}
                key: controller.host
                optional: false
          {{- end }}
          - name: CONTROLLER_PORT
          {{- if .Values.config.controller.port }}
            value: {{ .Values.config.controller.port | quote }}
          {{- else }}
            valueFrom:
              configMapKeyRef:
                name: {{ template "veidemann-api-gateway.configPrefix" . }}
                key: controller.port
                optional: false
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
