apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-frontier.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-frontier.name" . }}
    chart: {{ template "veidemann-frontier.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-frontier.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-frontier.name" . }}
        release: {{ .Release.Name }}
    {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | nindent 8 }}
    {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: workdir
          emptyDir: {}
        - name: log4j-config
          configMap:
            name: {{ template "veidemann-frontier.configPrefix" . }}
            items:
              - key: log4j2.xml
                path: log4j2.xml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ template "veidemann-frontier.configPrefix" . }}-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: {{ default .Values.global.veidemann.rethinkdb.host .Values.config.rethinkdb.host | quote }}
            - name: DB_PORT
              value: {{ default .Values.global.veidemann.rethinkdb.port .Values.config.rethinkdb.port | quote }}
            - name: DB_NAME
              value: {{ default .Values.global.veidemann.rethinkdb.name .Values.config.rethinkdb.name | quote }}
            - name: API_PORT
              value: {{ .Values.service.port | quote }}
            - name: ROBOTS_EVALUATOR_HOST
            {{- if .Values.config.robotsEvaluator.host }}
              value: {{ .Values.config.robotsEvaluator.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-frontier.configPrefix" . }}
                  key: robotsEvaluator.host
            {{- end }}
            - name: ROBOTS_EVALUATOR_PORT
            {{- if .Values.config.robotsEvaluator.port }}
              value: {{ .Values.config.robotsEvaluator.port | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-frontier.configPrefix" . }}
                  key: robotsEvaluator.port
            {{- end }}
            - name: DNS_RESOLVER_HOST
            {{- if .Values.config.dnsResolver.host }}
              value: {{ .Values.config.dnsResolver.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-frontier.configPrefix" . }}
                  key: dnsResolver.host
            {{- end }}
            - name: DNS_RESOLVER_PORT
            {{- if .Values.config.dnsResolver.port }}
              value: {{ .Values.config.dnsResolver.port | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-frontier.configPrefix" . }}
                  key: dnsResolver.port
            {{- end }}
            - name: OOS_HANDLER_HOST
            {{- if .Values.config.oosHandler.host }}
              value: {{ .Values.config.oosHandler.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-frontier.configPrefix" . }}
                  key: oosHandler.host
            {{- end }}
            - name: OOS_HANDLER_PORT
            {{- if .Values.config.oosHandler.port }}
              value: {{ .Values.config.oosHandler.port | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "veidemann-frontier.configPrefix" . }}
                  key: oosHandler.port
            {{- end }}
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: {{ .Values.config.terminationGracePeriodSeconds | quote }}
            - name: JAVA_OPTS
              value: {{ default .Values.config.javaOpts | quote }}
            - name: JAEGER_SERVICE_NAME
              value: {{ include "veidemann-frontier.fullname" . | quote }}
            - name: JAEGER_AGENT_HOST
              value: {{ default .Values.global.veidemann.jaeger.agent.host .Values.config.jaeger.agent.host | quote }}
            - name: JAEGER_AGENT_PORT
              value: {{ default .Values.global.veidemann.jaeger.agent.port .Values.config.jaeger.agent.port | quote }}
            {{- if or .Values.global.veidemann.jaeger.sampler.type .Values.config.jaeger.sampler.type }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ default .Values.global.veidemann.jaeger.sampler.type .Values.config.jaeger.sampler.type | quote }}
            {{- end }}
            {{- if or .Values.global.veidemann.jaeger.sampler.param .Values.config.jaeger.sampler.param }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ default .Values.global.veidemann.jaeger.sampler.param .Values.config.jaeger.sampler.param | quote }}
            {{- end }}
            - name: JAVA_TOOL_OPTIONS
              value: "-Dfile.encoding=UTF-8"
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
