apiVersion: v1
kind: Service
metadata:
  name: {{ template "veidemann-frontier.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-frontier.name" . }}
    chart: {{ template "veidemann-frontier.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: veidemann
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    component: {{ template "veidemann-frontier.name" . }}
    release: {{ .Release.Name }}
