apiVersion: v1
kind: Service
metadata:
  name: {{ template "veidemann-dnsresolver.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-dnsresolver.name" . }}
    chart: {{ template "veidemann-dnsresolver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalGrpcPort }}
      targetPort: {{ .Values.service.internalGrpcPort }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.externalDnsPort }}
      targetPort: {{ .Values.service.internalDnsPort }}
      protocol: TCP
      name: dnsTcp
  selector:
    component: {{ template "veidemann-dnsresolver.name" . }}
    release: {{ .Release.Name }}
