apiVersion: v1
kind: Service
metadata:
  name: {{ template "veidemann-dnsresolver.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-dnsresolver.name" . }}
    chart: {{ template "veidemann-dnsresolver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: veidemann
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalGrpcPort }}
      targetPort: {{ .Values.service.internalGrpcPort }}
      protocol: TCP
      name: grpc
    - name: dns
      port: {{ .Values.service.externalDnsPort }}
      targetPort: {{ .Values.service.internalDnsPort }}
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.service.externalDnsPort }}
      targetPort: {{ .Values.service.internalDnsPort }}
      protocol: TCP
    - name: http-metrics
      port: {{ .Values.service.externalMetricsPort }}
      targetPort: http-metrics

  selector:
    component: {{ template "veidemann-dnsresolver.name" . }}
    release: {{ .Release.Name }}
