apiVersion: v1
data:
  grafana.ini: W2F1dGguYW5vbnltb3VzXQplbmFibGVkID0gdHJ1ZQpbc2VydmVyXQpyb290X3VybCA9IGh0dHBzOi8vdmVpZGVtYW5uLnN0YWdlL2dyYWZhbmEvCg==
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
type: Opaque
