# Default values for veidemann-dnsresolver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-dns-resolver
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  internalGrpcPort: 8053
  externalGrpcPort: 8053
  internalDnsPort: 53
  externalDnsPort: 53
  externalMetricsPort: 9153
  internalMetricsPort: 9153
  internalHealthPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  db:
    host: rethinkdb-proxy
    port: 28015
    name: veidemann
    secretName: rethinkdb
  livenessProbe:
    httpGet:
      path: /health
      port: http-health
    initialDelaySeconds: 15
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /health
      port: http-health
    initialDelaySeconds: 3
    periodSeconds: 3
  jaeger:
    agent:
      host: $(NODE_NAME)
      port: 5775
    sampler:
      type: probabilistic
      param: 0.1
  contentWriter:
    host: $(NODE_NAME)
    port: 4340
  dnsServer: "8.8.8.8"
