# Default values for veidemann-dnsresolver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-dns-resolver
  pullPolicy: IfNotPresent
  # tag:latest

service:
  type: ClusterIP
  internalGrpcPort: 8053
  externalGrpcPort: 8053
  internalDnsPort: 53
  externalDnsPort: 53
  externalMetricsPort: 9153
  internalMetricsPort: 9153
  internalHealthPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  db:
    host: rethinkdb-proxy
    port: 28015
    name: veidemann
    secretName: rethinkdb
  jaeger:
    agent:
      host: $(NODE_NAME)
      port: 5775
    sampler:
      type: probabilistic
      param: 0.1
  contentWriter:
    host: $(NODE_NAME)
    port: 4340
  dnsServer: "8.8.8.8"
