{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rethinkdb.serviceAccountName" . }}
  labels:
{{ include "rethinkdb.labels" . | indent 4 }}
{{- end -}}
