# Default values for veidemann-dns-resolver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-dns-resolver
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  internalGrpcPort: 8053
  externalGrpcPort: 8053
  internalDnsPort: 53
  externalDnsPort: 53
  externalMetricsPort: 9153
  internalMetricsPort: 9153
  internalHealthPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /health
    port: http-health
  initialDelaySeconds: 15
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: http-health
  initialDelaySeconds: 15
  periodSeconds: 15

# global overrides config
global:
  veidemann:
    mesh:
      host: ""
      port: ""

config:
  contentWriter:
    host: ""
    port: ""

  dnsServer: "8.8.8.8"
