apiVersion: v1
kind: Service
metadata:
  name: {{ template "veidemann-contentexplorer.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-contentexplorer.name" . }}
    chart: {{ template "veidemann-contentexplorer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    component: {{ template "veidemann-contentexplorer.name" . }}
    release: {{ .Release.Name }}
