kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: veidemann-invalidwarcs
  namespace: default
  labels:
    app.kubernetes.io/instance: local
    app.kubernetes.io/part-of: veidemann
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
