apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "namerd.fullname" . }}-config
  labels:
    app: {{ template "namerd.name" . }}
    chart: {{ template "namerd.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
