apiVersion: v1
kind: Service
metadata:
  name: {{ template "veidemann-ooshandler.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-ooshandler.name" . }}
    chart: {{ template "veidemann-ooshandler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: veidemann
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-ooshandler
      port: {{ .Values.service.externalOosHandlerPort }}
      targetPort: http-ooshandler
    - name: http-metrics
      port: {{ .Values.service.externalMetricsPort }}
      targetPort: http-metrics

  selector:
    component: {{ template "veidemann-ooshandler.name" . }}
    release: {{ .Release.Name }}
