apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "veidemann-db-initializer.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-db-initializer.name" . }}
    chart: {{ template "veidemann-db-initializer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "veidemann-db-initializer.fullname" . }}
    spec:
      restartPolicy: {{ .Values.image.restartPolicy | quote }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ template "veidemann-db-initializer.configPrefix" . }}-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: {{ default .Values.global.veidemann.rethinkdb.host .Values.config.rethinkdb.host | quote }}
            - name: DB_PORT
              value: {{ default .Values.global.veidemann.rethinkdb.port .Values.config.rethinkdb.port | quote }}
            - name: DB_NAME
              value: {{ default .Values.global.veidemann.rethinkdb.name .Values.config.rethinkdb.name | quote }}
