apiVersion: v1
kind: Secret
metadata:
  name: {{ template "webhook-receiver-proxy.fullname" . }}
  labels:
    app: {{ template "webhook-receiver-proxy.name" . }}
    chart: {{ template "webhook-receiver-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.config.keys }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
