dependencies:
  - name: cassandra
    version: 0.5.4
    repository: file://../cassandra
    condition: provisionDataStore.cassandra
  - name: elasticsearch
    version: ^0.4.1
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: provisionDataStore.elasticsearch
