apiVersion: v1
kind: Service
metadata:
  name: "{{ template "rethinkdb.fullname" . }}-cluster"
  labels:
{{ include "rethinkdb.labels" . | indent 4 }}
    app.kubernetes.io/component: cluster
  annotations:
  {{- if .Values.cluster.service.annotations }}
{{ toYaml .Values.cluster.service.annotations | indent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.ports.cluster }}
      targetPort: cluster
  selector:
    app.kubernetes.io/name: {{ include "rethinkdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cluster
