{{- if .Values.cluster.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
{{ include "rethinkdb.labels" . | indent 4 }}
    app.kubernetes.io/component: cluster
  name: {{ template "rethinkdb.fullname" . }}
provisioner: {{ .Values.cluster.storageClass.provisioner }}
parameters:
{{- range $key, $value := .Values.cluster.storageClass.parameters }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
