{{- if not (eq .Values.proxy.kind "Deployment") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rethinkdb.fullname" . }}-admin
  labels:
{{ include "rethinkdb.labels" . | indent 4 }}
    app.kubernetes.io/component: rethinkdb-admin
spec:
  replicas: 1
  minReadySeconds: {{ .Values.admin.minReadySeconds }}
  updateStrategy:
{{ toYaml .Values.admin.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rethinkdb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: rethinkdb-admin
  template:
    metadata:
      name: {{ template "rethinkdb.fullname" . }}-admin
      labels:
        app.kubernetes.io/name: {{ include "rethinkdb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: rethinkdb-admin
      annotations:
      {{- if .Values.admin.podAnnotations }}
{{ toYaml .Values.admin.podAnnotations | indent 8 }}
      {{- end }}
    spec:
{{- if .Values.admin.priorityClassName }}
      priorityClassName: {{ .Values.admin.priorityClassName | quote }}
{{- end }}
      serviceAccountName: {{ template "rethinkdb.serviceAccountName" . }}
      containers:
        - name: {{ template "rethinkdb.name" . }}-admin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cluster
              containerPort: {{ .Values.ports.cluster }}
            - name: driver
              containerPort: {{ .Values.ports.driver }}
            - name: http-admin
              containerPort: {{ .Values.ports.admin }}
          args:
            - "--bind"
            - "$(POD_IP)"
            - "--no-update-check"
            {{- if .Values.admin.driverTLS.enabled }}
            - "--driver-tls-key"
            - "/secrets/driver-key.pem"
            - "--driver-tls-cert"
            - "/secrets/driver-cert.pem"
            {{- end }}
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: {{ template "rethinkdb.fullname" . }}-cluster
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rethinkdb.fullname" . }}
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
{{ toYaml .Values.admin.resources | indent 12 }}
    {{- if .Values.admin.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.admin.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.admin.tolerations }}
      tolerations:
{{ toYaml .Values.admin.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.admin.affinity }}
      affinity:
{{ toYaml .Values.admin.affinity | indent 8 }}
    {{- end }}
      volumes:
        - name: secrets
          projected:
            sources:
            - secret:
                name: {{ template "rethinkdb.fullname" . }}
{{- end }}
