{{- if eq .Values.proxy.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "rethinkdb.fullname" . }}-proxy
  labels:
{{ include "rethinkdb.labels" . | indent 4 }}
    app.kubernetes.io/component: rethinkdb-proxy
spec:
  minReadySeconds: {{ .Values.proxy.minReadySeconds }}
  updateStrategy:
{{ toYaml .Values.proxy.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rethinkdb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: rethinkdb-proxy
  template:
    metadata:
      name: {{ template "rethinkdb.fullname" . }}-proxy
      labels:
        app.kubernetes.io/name: {{ include "rethinkdb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: rethinkdb-proxy
      annotations:
      {{- if .Values.proxy.podAnnotations }}
{{ toYaml .Values.proxy.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      dnsPolicy: {{ .Values.proxy.dnsPolicy }}
{{- if .Values.proxy.priorityClassName }}
      priorityClassName: "{{ .Values.proxy.priorityClassName }}"
{{- end }}
      serviceAccountName: {{ template "rethinkdb.serviceAccountName" . }}
      containers:
        - name: {{ template "rethinkdb.name" . }}-proxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cluster
              containerPort: {{ .Values.ports.cluster }}
            - name: driver
              containerPort: {{ .Values.ports.driver }}
          args:
            - "--bind"
            - "$(POD_IP)"
            - "--no-update-check"
            - "--no-http-admin"
            {{- if .Values.proxy.driverTLS.enabled }}
            - "--driver-tls-key"
            - "/secrets/driver-key.pem"
            - "--driver-tls-cert"
            - "/secrets/driver-cert.pem"
            {{- end }}
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: {{ template "rethinkdb.fullname" . }}-cluster
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rethinkdb.fullname" . }}
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
      hostNetwork: {{ .Values.proxy.hostNetwork }}
    {{- if .Values.proxy.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.proxy.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.proxy.tolerations }}
      tolerations:
{{ toYaml .Values.proxy.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.proxy.affinity }}
      affinity:
{{ toYaml .Values.proxy.affinity | indent 8 }}
    {{- end }}
      volumes:
        - name: secrets
          projected:
            sources:
            - secret:
                name: {{ template "rethinkdb.fullname" . }}
{{- end }}
