# Default values for veidemann helm chart minikube install
tags:
  database: true
  mesh: false
  validation: true
  dashboard: true
  idp: true
  tracing: false
  metrics: false

.hostname: &hostname veidemann.local

.ingress: &ingress
  enabled: true
  hosts:
  - *hostname
  tls:
  - secretName: local-veidemann-ingress-tls-cert
    hosts:
    - *hostname

.issuer: &issuer "https://veidemann.local/dex"

veidemann-dashboard:
  ingress:
    <<: *ingress
  config:
    issuer: *issuer

veidemann-dashboard-documentation:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
  baseUrl: https://veidemann.local/veidemann/docs

veidemann-api-gateway:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"

veidemann-warcvalidator-api:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"

veidemann-contentexplorer:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"

veidemann-controller:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  config:
    issuer: *issuer

rethinkdb:
  cluster:
    rethinkCacheSize: "auto"
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "5Gi"

jaeger:
  agent:
    dnsPolicy: ClusterFirstWithHostNet
    useHostNetwork: true

dex:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
  certs:
    web:
      altNames:
        - *hostname
    grpc:
      altNames:
        - *hostname

  config:
    issuer: "https://veidemann.local/dex"
    web:
      allowedOrigins:
      - https://veidemann.local
      - https://localhost:4200
    enablePasswordDB: true
    staticPasswords:
    - email: "admin@example.com"
      # bcrypt hash of the string "password"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    staticClients:
    - id: veidemann-dashboard
      redirectURIs:
      - "https://veidemann.local/veidemann"
      - "https://localhost:4200/veidemann"
      name: "Veidemann Admin Dashboard"
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    - id: veidemann-cli
      public: true
      name: "Veidemann CLI"
      secret: cli-app-secret
    - id: veidemann-api
      name: "Veidemann API"
      secret: VerySecret
      trustedPeers:
      - veidemann-cli
      - veidemann-dashboard
