# Default values for veidemann helm chart minikube install
tags:
  database: true
  dashboard: true
  idp: true
  tracing: true
  metrics: true

.hostname: &hostname veidemann.local

.ingress: &ingress
  enabled: true
  hosts:
    - *hostname
  tls:
    - secretName: local-veidemann-ingress-tls-cert
      hosts:
        - *hostname

.issuer: &issuer "https://veidemann.local/dex"

.latest_image: &latest-image
  image:
    tag: latest
    pullPolicy: Always

global:
  veidemann:
    rethinkdb:
      host: local-rethinkdb-proxy

veidemann-cache:
  cache:
    <<: *latest-image
  podAnnotations:
    linkerd.io/inject: "enabled"

veidemann-robotsevaluator-service:
  <<: *latest-image
  podAnnotations:
    linkerd.io/inject: "enabled"
    config.linkerd.io/skip-outbound-ports: "14250"
  annotations:
    sidecar.jaegertracing.io/inject: "true"

veidemann-dns-resolver:
  <<: *latest-image
  podAnnotations:
    linkerd.io/inject: "enabled"

veidemann-ooshandler:
  <<: *latest-image
  podAnnotations:
    linkerd.io/inject: "enabled"

veidemann-db-initializer:
  <<: *latest-image
  annotations:
    "helm.sh/hook": "post-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"

veidemann-metrics:
  affinity: ""

veidemann-dashboard:
  <<: *latest-image
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
  config:
    issuer: *issuer

veidemann-dashboard-documentation:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
  baseUrl: https://veidemann.local/veidemann/docs

veidemann-warcvalidator-api:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"

veidemann-contentexplorer:
  <<: *latest-image
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"

veidemann-contentwriter:
  <<: *latest-image
  podAnnotations:
    linkerd.io/inject: "enabled"
    config.linkerd.io/skip-outbound-ports: "14250"
  annotations:
    sidecar.jaegertracing.io/inject: "true"

veidemann-controller:
  <<: *latest-image
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  config:
    issuer: *issuer
  podAnnotations:
    linkerd.io/inject: "enabled"
    config.linkerd.io/skip-outbound-ports: "14250"
    config.linkerd.io/skip-inbound-ports: "7700"
  annotations:
    sidecar.jaegertracing.io/inject: "true"

veidemann-harvester:
  browserController:
    <<: *latest-image
  proxy:
    <<: *latest-image
  podAnnotations:
    linkerd.io/inject: "enabled"
    config.linkerd.io/skip-outbound-ports: "3128,14250"
  annotations:
    sidecar.jaegertracing.io/inject: "true"

veidemann-frontier:
  <<: *latest-image
  podAnnotations:
    linkerd.io/inject: "enabled"
    config.linkerd.io/skip-outbound-ports: "14250"
  annotations:
    sidecar.jaegertracing.io/inject: "true"

rethinkdb:
  cluster:
    cores: 1
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 4Gi

rethinkdb-exporter:
  rethinkdb_exporter:
    db:
      addr: "local-rethinkdb-proxy:28015"
      secretName: local-veidemann-rethinkdb-env
    count_rows: false

jaeger:
  storage:
    type: memory
    options:
      memory:
        max-traces: 1000

dex:
  ingress:
    <<: *ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
  certs:
    web:
      altNames:
        - *hostname
    grpc:
      altNames:
        - *hostname

  config:
    issuer: "https://veidemann.local/dex"
    web:
      allowedOrigins:
        - https://veidemann.local
        - https://localhost:4200
    enablePasswordDB: true
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the string "password"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    staticClients:
      - id: veidemann-dashboard
        redirectURIs:
          - "https://veidemann.local/veidemann"
          - "https://localhost:4200/veidemann"
        name: "Veidemann Admin Dashboard"
        secret: ZXhhbXBsZS1hcHAtc2VjcmV0
      - id: veidemann-cli
        public: true
        name: "Veidemann CLI"
        secret: cli-app-secret
      - id: veidemann-api
        name: "Veidemann API"
        secret: VerySecret
        trustedPeers:
          - veidemann-cli
          - veidemann-dashboard
