apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "linkerd.fullname" . }}
  labels:
    app: {{ template "linkerd.name" . }}
    chart: {{ template "linkerd.chart"  . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "linkerd.name" . }}
        release: {{ .Release.Name }}
    {{- with .Values.daemonSet.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      hostNetwork: {{ .Values.daemonSet.hostNetwork }}
      dnsPolicy:  {{ .Values.daemonSet.dnsPolicy }}
      volumes:
        - name: l5d-config
          configMap:
            name: "{{ template "linkerd.fullname" . }}-config"
      {{- if .Values.tls }}
        - name: certificates
          secret:
            secretName: {{ .Values.tls.secretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          args:
            - /io.buoyant/linkerd/config/config.yaml
          ports:
{{ toYaml .Values.ports | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          volumeMounts:
            - name: "l5d-config"
              mountPath: "/io.buoyant/linkerd/config"
              readOnly: true
          {{- if .Values.tls }}
            - name: "certificates"
              mountPath: "/io.buoyant/linkerd/certs"
              readOnly: true
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}

        # Kubectl
        - name: {{ .Chart.Name }}-kubectl
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          args:
            - "proxy"
            - "-p"
            - "8001"
          resources:
{{ toYaml .Values.kubectl.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
