# grant linkerd/namerd permissions to enable service discovery
{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "linkerd.fullname" . }}
  labels:
    app: {{ template "linkerd.name" . }}
    chart: {{ template "linkerd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
    - services
    - pods
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - extensions
  resources:
    - ingresses
    - ingresses/status
  verbs:
    - get
    - watch
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "linkerd.fullname" . }}
  labels:
    app: {{ template "linkerd.name" . }}
    chart: {{ template "linkerd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "linkerd.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "linkerd.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}