# Specs for the RethinkDB image
image:
  repository: codylundquist/helm-rethinkdb-cluster
  tag: 0.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# RethinkDB Cluster Config
cluster:
  replicas: 3
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 16Gi
    # requests:
    #   cpu: 500m
    #   memory: 8Gi
  podAnnotations: {}
  affinity: {}
  tolerations: []
  terminationGracePeriodSeconds:
  service:
    annotations: {}
  storageClass:
    enabled: false
    # provisioner: kubernetes.io/gce-pd
    # parameters:
    #   type: pd-ssd
  persistentVolume:
    enabled: false
    # If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    # storageClass: fast
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
  # If peristentVolume not enabled override default volumes
  volumes: []
  # If persistentVolume not enabled
  volumeMounts: []
  # RethinkDB Cache Size in MB
  rethinkCacheSize: 100
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
# RethinkDB Proxy Config
proxy:
  replicas: 1
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 512Mi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi
  podAnnotations: {}
  service:
    annotations: {}
    type: ClusterIP
    clusterIP: ""
    # List of IP addresses at which the proxy service is available
    # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#external-ips
    #
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  # Secure your RethinkDB Driver using TLS.
  # Hint: You'll need to create your cert with a domain that is pointing
  # to the External IP Address returned from the LoadBalancer
  # More Info: https://www.rethinkdb.com/docs/security/#using-tls
  driverTLS:
    enabled: false
    # key: |-
    #   << RSA PRIVATE KEY >>
    # cert: |-
    #   << CERTIFICATE >>

# RethinkDB Ports
ports:
  cluster: 29015
  driver: 28015
  admin: 8080

# RethinkDB Admin Password
rethinkdbPassword: rethinkdb

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
