apiVersion: v1
kind: Secret
metadata:
  name: {{ template "veidemann.fullname" . }}
  labels:
    app: {{ template "veidemann.name" . }}
    chart: {{ template "veidemann.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
