{{- if .Values.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "veidemann.configPrefix" . }}-ingress-tls-cert
  labels:
    app: {{ template "veidemann.name" . }}
    chart: {{ template "veidemann.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: "kubernetes.io/tls"
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
