apiVersion: v1
kind: Secret
metadata:
  name: {{ template "veidemann.configPrefix" . }}-rethinkdb-env
  labels:
    app: {{ template "veidemann.name" . }}
    chart: {{ template "veidemann.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_USER: {{ default .Values.default.rethinkdb.user .Values.config.rethinkdb.user | b64enc | quote }}
  DB_PASSWORD: {{ default .Values.default.rethinkdb.password .Values.config.rethinkdb.password | b64enc | quote }}
