apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-contentexplorer.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-contentexplorer.name" . }}
    chart: {{ template "veidemann-contentexplorer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-contentexplorer.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-contentexplorer.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - emptyDir: {}
          name: workdir
        - name: warcs
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "veidemann-contentexplorer.claimName" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: log4j-config
          configMap:
            name: {{ template "veidemann-contentexplorer.configPrefix" . }}
            items:
            - key: log4j2.xml
              path: log4j2.xml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ template "veidemann-contentexplorer.configPrefix" . }}-rethinkdb-env
                optional: false
            - secretRef:
                name: {{ template "veidemann-contentexplorer.configPrefix" . }}-rethinkdb-env
                optional: false
          env:
            - name: API_PORT
              value: {{ .Values.service.port | quote }}
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - mountPath: /warcs
              name: warcs
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
