apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-contentexplorer.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-contentexplorer.name" . }}
    chart: {{ template "veidemann-contentexplorer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-contentexplorer.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: veidemann
        component: {{ template "veidemann-contentexplorer.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - emptyDir: {}
          name: workdir
        - name: warcs
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "veidemann-contentexplorer.claimName" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: log4j-config
          configMap:
            name: {{ template "veidemann-contentexplorer.configPrefix" . }}
            items:
            - key: log4j2.xml
              path: log4j2.xml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ template "veidemann-contentexplorer.configPrefix" . }}-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: {{ default .Values.global.veidemann.rethinkdb.host .Values.config.rethinkdb.host | quote }}
            - name: DB_PORT
              value: {{ default .Values.global.veidemann.rethinkdb.port .Values.config.rethinkdb.port | quote }}
            - name: DB_NAME
              value: {{ default .Values.global.veidemann.rethinkdb.name .Values.config.rethinkdb.name | quote }}
            - name: API_PORT
              value: {{ .Values.service.port | quote }}
            - name: JAEGER_SERVICE_NAME
              value: {{ include "veidemann-contentexplorer.fullname" . | quote }}
            - name: JAEGER_AGENT_HOST
              value: {{ default .Values.global.veidemann.jaeger.agent.host .Values.config.jaeger.agent.host | quote }}
            - name: JAEGER_AGENT_PORT
              value: {{ default .Values.global.veidemann.jaeger.agent.port .Values.config.jaeger.agent.port | quote }}
            {{- if or .Values.global.veidemann.jaeger.sampler.type .Values.config.jaeger.sampler.type }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ default .Values.global.veidemann.jaeger.sampler.type .Values.config.jaeger.sampler.type | quote }}
            {{- end }}
            {{- if or .Values.global.veidemann.jaeger.sampler.param .Values.config.jaeger.sampler.param }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ default .Values.global.veidemann.jaeger.sampler.param .Values.config.jaeger.sampler.param | quote }}
            {{- end }}
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - mountPath: /warcs
              name: warcs
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
