# Default values for veidemann-dnsresolver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-dnsresolver
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 50052

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  db:
    host: rethinkdb-proxy
    port: 28015
    secretName: rethinkdb
  jaeger:
    agent:
      host: $(NODE_NAME)
      port: 5775
    sampler:
      type: probabilistic
      param: 0.1
  contentWriter:
    host: $(NODE_NAME)
    port: 4340
  dnsServer: "8.8.8.8"
