apiVersion: v1
appVersion: 0.1.10
description: A Helm chart for Kubernetes
name: veidemann-api-gateway
version: 1.0.0
kubeVersion: ">=1.9.0"
sources:
  - https://github.com/nlnwa/veidemann-api-gateway
